/*
 * This file is generated by jOOQ.
 */
package com.nacho.entities.jooq.db.tables.records;


import com.nacho.entities.jooq.db.tables._PrismaMigrations;
import com.nacho.entities.jooq.db.tables.interfaces.I_PrismaMigrations;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _PrismaMigrationsRecord extends UpdatableRecordImpl<_PrismaMigrationsRecord> implements I_PrismaMigrations {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public._prisma_migrations.id</code>.
     */
    @Override
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.id</code>.
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public._prisma_migrations.checksum</code>.
     */
    @Override
    public void setChecksum(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.checksum</code>.
     */
    @Override
    public String getChecksum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public._prisma_migrations.finished_at</code>.
     */
    @Override
    public void setFinishedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.finished_at</code>.
     */
    @Override
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public._prisma_migrations.migration_name</code>.
     */
    @Override
    public void setMigrationName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.migration_name</code>.
     */
    @Override
    public String getMigrationName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public._prisma_migrations.logs</code>.
     */
    @Override
    public void setLogs(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.logs</code>.
     */
    @Override
    public String getLogs() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public._prisma_migrations.rolled_back_at</code>.
     */
    @Override
    public void setRolledBackAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.rolled_back_at</code>.
     */
    @Override
    public OffsetDateTime getRolledBackAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public._prisma_migrations.started_at</code>.
     */
    @Override
    public void setStartedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.started_at</code>.
     */
    @Override
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public._prisma_migrations.applied_steps_count</code>.
     */
    @Override
    public void setAppliedStepsCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public._prisma_migrations.applied_steps_count</code>.
     */
    @Override
    public Integer getAppliedStepsCount() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(I_PrismaMigrations from) {
        setId(from.getId());
        setChecksum(from.getChecksum());
        setFinishedAt(from.getFinishedAt());
        setMigrationName(from.getMigrationName());
        setLogs(from.getLogs());
        setRolledBackAt(from.getRolledBackAt());
        setStartedAt(from.getStartedAt());
        setAppliedStepsCount(from.getAppliedStepsCount());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends I_PrismaMigrations> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _PrismaMigrationsRecord
     */
    public _PrismaMigrationsRecord() {
        super(_PrismaMigrations._PRISMA_MIGRATIONS);
    }

    /**
     * Create a detached, initialised _PrismaMigrationsRecord
     */
    public _PrismaMigrationsRecord(String id, String checksum, OffsetDateTime finishedAt, String migrationName, String logs, OffsetDateTime rolledBackAt, OffsetDateTime startedAt, Integer appliedStepsCount) {
        super(_PrismaMigrations._PRISMA_MIGRATIONS);

        setId(id);
        setChecksum(checksum);
        setFinishedAt(finishedAt);
        setMigrationName(migrationName);
        setLogs(logs);
        setRolledBackAt(rolledBackAt);
        setStartedAt(startedAt);
        setAppliedStepsCount(appliedStepsCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised _PrismaMigrationsRecord
     */
    public _PrismaMigrationsRecord(com.nacho.entities.jooq.db.tables.pojos._PrismaMigrations value) {
        super(_PrismaMigrations._PRISMA_MIGRATIONS);

        if (value != null) {
            setId(value.getId());
            setChecksum(value.getChecksum());
            setFinishedAt(value.getFinishedAt());
            setMigrationName(value.getMigrationName());
            setLogs(value.getLogs());
            setRolledBackAt(value.getRolledBackAt());
            setStartedAt(value.getStartedAt());
            setAppliedStepsCount(value.getAppliedStepsCount());
            resetChangedOnNotNull();
        }
    }
}
