/*
 * This file is generated by jOOQ.
 */
package com.nacho.entities.jooq.db.tables.records;


import com.nacho.entities.jooq.db.tables.Announcements;
import com.nacho.entities.jooq.db.tables.interfaces.IAnnouncements;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnnouncementsRecord extends UpdatableRecordImpl<AnnouncementsRecord> implements IAnnouncements {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Announcements.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Announcements.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Announcements.title</code>.
     */
    @Override
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Announcements.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.Announcements.text</code>.
     */
    @Override
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Announcements.text</code>.
     */
    @Override
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.Announcements.image_url</code>.
     */
    @Override
    public void setImageUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.Announcements.image_url</code>.
     */
    @Override
    public String getImageUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.Announcements.timestamp</code>.
     */
    @Override
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.Announcements.timestamp</code>.
     */
    @Override
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAnnouncements from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setText(from.getText());
        setImageUrl(from.getImageUrl());
        setTimestamp(from.getTimestamp());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IAnnouncements> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnnouncementsRecord
     */
    public AnnouncementsRecord() {
        super(Announcements.ANNOUNCEMENTS);
    }

    /**
     * Create a detached, initialised AnnouncementsRecord
     */
    public AnnouncementsRecord(Integer id, String title, String text, String imageUrl, LocalDateTime timestamp) {
        super(Announcements.ANNOUNCEMENTS);

        setId(id);
        setTitle(title);
        setText(text);
        setImageUrl(imageUrl);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AnnouncementsRecord
     */
    public AnnouncementsRecord(com.nacho.entities.jooq.db.tables.pojos.Announcements value) {
        super(Announcements.ANNOUNCEMENTS);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setText(value.getText());
            setImageUrl(value.getImageUrl());
            setTimestamp(value.getTimestamp());
            resetChangedOnNotNull();
        }
    }
}
