/*
 * This file is generated by jOOQ.
 */
package com.nacho.entities.jooq.db.tables.records;


import com.nacho.entities.jooq.db.tables.Pricedata;
import com.nacho.entities.jooq.db.tables.interfaces.IPricedata;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PricedataRecord extends UpdatableRecordImpl<PricedataRecord> implements IPricedata {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.PriceData.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.PriceData.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.PriceData.tick</code>.
     */
    @Override
    public void setTick(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.PriceData.tick</code>.
     */
    @Override
    public String getTick() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.PriceData.timestamp</code>.
     */
    @Override
    public void setTimestamp(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.PriceData.timestamp</code>.
     */
    @Override
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.PriceData.valueKAS</code>.
     */
    @Override
    public void setValuekas(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.PriceData.valueKAS</code>.
     */
    @Override
    public Double getValuekas() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.PriceData.valueUSD</code>.
     */
    @Override
    public void setValueusd(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.PriceData.valueUSD</code>.
     */
    @Override
    public Double getValueusd() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.PriceData.change24h</code>.
     */
    @Override
    public void setChange24h(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.PriceData.change24h</code>.
     */
    @Override
    public Double getChange24h() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPricedata from) {
        setId(from.getId());
        setTick(from.getTick());
        setTimestamp(from.getTimestamp());
        setValuekas(from.getValuekas());
        setValueusd(from.getValueusd());
        setChange24h(from.getChange24h());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IPricedata> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PricedataRecord
     */
    public PricedataRecord() {
        super(Pricedata.PRICEDATA);
    }

    /**
     * Create a detached, initialised PricedataRecord
     */
    public PricedataRecord(Integer id, String tick, LocalDateTime timestamp, Double valuekas, Double valueusd, Double change24h) {
        super(Pricedata.PRICEDATA);

        setId(id);
        setTick(tick);
        setTimestamp(timestamp);
        setValuekas(valuekas);
        setValueusd(valueusd);
        setChange24h(change24h);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PricedataRecord
     */
    public PricedataRecord(com.nacho.entities.jooq.db.tables.pojos.Pricedata value) {
        super(Pricedata.PRICEDATA);

        if (value != null) {
            setId(value.getId());
            setTick(value.getTick());
            setTimestamp(value.getTimestamp());
            setValuekas(value.getValuekas());
            setValueusd(value.getValueusd());
            setChange24h(value.getChange24h());
            resetChangedOnNotNull();
        }
    }
}
