/*
 * This file is generated by jOOQ.
 */
package com.nacho.entities.jooq.db.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBalance extends Serializable {

    /**
     * Setter for <code>public.Balance.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>public.Balance.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>public.Balance.balance</code>.
     */
    public void setBalance(String value);

    /**
     * Getter for <code>public.Balance.balance</code>.
     */
    public String getBalance();

    /**
     * Setter for <code>public.Balance.holderId</code>.
     */
    public void setHolderid(Integer value);

    /**
     * Getter for <code>public.Balance.holderId</code>.
     */
    public Integer getHolderid();

    /**
     * Setter for <code>public.Balance.tokenTick</code>.
     */
    public void setTokentick(String value);

    /**
     * Getter for <code>public.Balance.tokenTick</code>.
     */
    public String getTokentick();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IBalance
     */
    public void from(IBalance from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IBalance
     */
    public <E extends IBalance> E into(E into);
}
