/*
 * This file is generated by jOOQ.
 */
package com.nacho.entities.jooq.db.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITokens extends Serializable {

    /**
     * Setter for <code>public.Tokens.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>public.Tokens.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>public.Tokens.username</code>.
     */
    public void setUsername(String value);

    /**
     * Getter for <code>public.Tokens.username</code>.
     */
    public String getUsername();

    /**
     * Setter for <code>public.Tokens.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>public.Tokens.password</code>.
     */
    public String getPassword();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITokens
     */
    public void from(ITokens from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITokens
     */
    public <E extends ITokens> E into(E into);
}
