/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFetchData extends Serializable {

    /**
     * Setter for <code>public.fetch_data.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>public.fetch_data.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>public.fetch_data.identifier</code>.
     */
    public void setIdentifier(String value);

    /**
     * Getter for <code>public.fetch_data.identifier</code>.
     */
    public String getIdentifier();

    /**
     * Setter for <code>public.fetch_data.data</code>.
     */
    public void setData(String value);

    /**
     * Getter for <code>public.fetch_data.data</code>.
     */
    public String getData();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IFetchData
     */
    public void from(IFetchData from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IFetchData
     */
    public <E extends IFetchData> E into(E into);
}
