/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.interfaces;


import java.io.Serializable;
import java.math.BigInteger;

import org.jooq.impl.AutoConverter;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IHolder extends Serializable {

    /**
     * Setter for <code>public.Holder.id</code>.
     */
    public void setId(BigInteger value);

    /**
     * Getter for <code>public.Holder.id</code>.
     */
    public BigInteger getId();

    /**
     * Setter for <code>public.Holder.address</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>public.Holder.address</code>.
     */
    public String getAddress();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IHolder
     */
    public void from(IHolder from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IHolder
     */
    public <E extends IHolder> E into(E into);
}
