/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.interfaces;


import java.io.Serializable;
import java.math.BigInteger;

import org.jooq.impl.AutoConverter;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface INftCollectionEntry extends Serializable {

    /**
     * Setter for <code>public.nft_collection_entry.id</code>.
     */
    public void setId(BigInteger value);

    /**
     * Getter for <code>public.nft_collection_entry.id</code>.
     */
    public BigInteger getId();

    /**
     * Setter for <code>public.nft_collection_entry.fk_collection</code>.
     */
    public void setFkCollection(BigInteger value);

    /**
     * Getter for <code>public.nft_collection_entry.fk_collection</code>.
     */
    public BigInteger getFkCollection();

    /**
     * Setter for <code>public.nft_collection_entry.edition</code>.
     */
    public void setEdition(Integer value);

    /**
     * Getter for <code>public.nft_collection_entry.edition</code>.
     */
    public Integer getEdition();

    /**
     * Setter for <code>public.nft_collection_entry.image</code>.
     */
    public void setImage(String value);

    /**
     * Getter for <code>public.nft_collection_entry.image</code>.
     */
    public String getImage();

    /**
     * Setter for <code>public.nft_collection_entry.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.nft_collection_entry.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.nft_collection_entry.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>public.nft_collection_entry.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.nft_collection_entry.attributes</code>.
     */
    public void setAttributes(String value);

    /**
     * Getter for <code>public.nft_collection_entry.attributes</code>.
     */
    public String getAttributes();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface INftCollectionEntry
     */
    public void from(INftCollectionEntry from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface INftCollectionEntry
     */
    public <E extends INftCollectionEntry> E into(E into);
}
