/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.interfaces;


import java.io.Serializable;
import java.math.BigInteger;

import org.jooq.impl.AutoConverter;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface INftBalance extends Serializable {

    /**
     * Setter for <code>public.nft_balance.id</code>.
     */
    public void setId(BigInteger value);

    /**
     * Getter for <code>public.nft_balance.id</code>.
     */
    public BigInteger getId();

    /**
     * Setter for <code>public.nft_balance.holder_id</code>.
     */
    public void setHolderId(BigInteger value);

    /**
     * Getter for <code>public.nft_balance.holder_id</code>.
     */
    public BigInteger getHolderId();

    /**
     * Setter for <code>public.nft_balance.fk_nft_entry</code>.
     */
    public void setFkNftEntry(Integer value);

    /**
     * Getter for <code>public.nft_balance.fk_nft_entry</code>.
     */
    public Integer getFkNftEntry();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface INftBalance
     */
    public void from(INftBalance from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface INftBalance
     */
    public <E extends INftBalance> E into(E into);
}
