/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.interfaces;


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

import org.jooq.impl.AutoConverter;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITransaction extends Serializable {

    /**
     * Setter for <code>public.Transaction.id</code>.
     */
    public void setId(BigInteger value);

    /**
     * Getter for <code>public.Transaction.id</code>.
     */
    public BigInteger getId();

    /**
     * Setter for <code>public.Transaction.fk_token</code>.
     */
    public void setFkToken(Integer value);

    /**
     * Getter for <code>public.Transaction.fk_token</code>.
     */
    public Integer getFkToken();

    /**
     * Setter for <code>public.Transaction.hashrev</code>.
     */
    public void setHashrev(String value);

    /**
     * Getter for <code>public.Transaction.hashrev</code>.
     */
    public String getHashrev();

    /**
     * Setter for <code>public.Transaction.p</code>.
     */
    public void setP(String value);

    /**
     * Getter for <code>public.Transaction.p</code>.
     */
    public String getP();

    /**
     * Setter for <code>public.Transaction.op</code>.
     */
    public void setOp(String value);

    /**
     * Getter for <code>public.Transaction.op</code>.
     */
    public String getOp();

    /**
     * Setter for <code>public.Transaction.amt</code>.
     */
    public void setAmt(String value);

    /**
     * Getter for <code>public.Transaction.amt</code>.
     */
    public String getAmt();

    /**
     * Setter for <code>public.Transaction.from</code>.
     */
    public void setFrom(String value);

    /**
     * Getter for <code>public.Transaction.from</code>.
     */
    public String getFrom();

    /**
     * Setter for <code>public.Transaction.to</code>.
     */
    public void setTo(String value);

    /**
     * Getter for <code>public.Transaction.to</code>.
     */
    public String getTo();

    /**
     * Setter for <code>public.Transaction.op_score</code>.
     */
    public void setOpScore(String value);

    /**
     * Getter for <code>public.Transaction.op_score</code>.
     */
    public String getOpScore();

    /**
     * Setter for <code>public.Transaction.fee_rev</code>.
     */
    public void setFeeRev(String value);

    /**
     * Getter for <code>public.Transaction.fee_rev</code>.
     */
    public String getFeeRev();

    /**
     * Setter for <code>public.Transaction.tx_accept</code>.
     */
    public void setTxAccept(String value);

    /**
     * Getter for <code>public.Transaction.tx_accept</code>.
     */
    public String getTxAccept();

    /**
     * Setter for <code>public.Transaction.op_accept</code>.
     */
    public void setOpAccept(String value);

    /**
     * Getter for <code>public.Transaction.op_accept</code>.
     */
    public String getOpAccept();

    /**
     * Setter for <code>public.Transaction.op_error</code>.
     */
    public void setOpError(String value);

    /**
     * Getter for <code>public.Transaction.op_error</code>.
     */
    public String getOpError();

    /**
     * Setter for <code>public.Transaction.checkpoint</code>.
     */
    public void setCheckpoint(String value);

    /**
     * Getter for <code>public.Transaction.checkpoint</code>.
     */
    public String getCheckpoint();

    /**
     * Setter for <code>public.Transaction.max</code>.
     */
    public void setMax(BigInteger value);

    /**
     * Getter for <code>public.Transaction.max</code>.
     */
    public BigInteger getMax();

    /**
     * Setter for <code>public.Transaction.lim</code>.
     */
    public void setLim(BigInteger value);

    /**
     * Getter for <code>public.Transaction.lim</code>.
     */
    public BigInteger getLim();

    /**
     * Setter for <code>public.Transaction.pre</code>.
     */
    public void setPre(BigInteger value);

    /**
     * Getter for <code>public.Transaction.pre</code>.
     */
    public BigInteger getPre();

    /**
     * Setter for <code>public.Transaction.mts_add</code>.
     */
    public void setMtsAdd(BigInteger value);

    /**
     * Getter for <code>public.Transaction.mts_add</code>.
     */
    public BigInteger getMtsAdd();

    /**
     * Setter for <code>public.Transaction.mts_mod</code>.
     */
    public void setMtsMod(BigInteger value);

    /**
     * Getter for <code>public.Transaction.mts_mod</code>.
     */
    public BigInteger getMtsMod();

    /**
     * Setter for <code>public.Transaction.dec</code>.
     */
    public void setDec(Integer value);

    /**
     * Getter for <code>public.Transaction.dec</code>.
     */
    public Integer getDec();

    /**
     * Setter for <code>public.Transaction.timestamp</code>.
     */
    public void setTimestamp(LocalDateTime value);

    /**
     * Getter for <code>public.Transaction.timestamp</code>.
     */
    public LocalDateTime getTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITransaction
     */
    public void from(ITransaction from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITransaction
     */
    public <E extends ITransaction> E into(E into);
}
