/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db;


import com.katbrew.entities.jooq.db.tables.Transaction;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TRANSACTION_FK_INDEX = Internal.createIndex(DSL.name("transaction_fk_index"), Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.FK_TOKEN }, false);
    public static final Index TRANSACTION_OP_SCORE_IDX = Internal.createIndex(DSL.name("Transaction_op_score_idx"), Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.OP_SCORE }, false);
}
