/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db;


import com.katbrew.entities.jooq.db.tables.Advertisements;
import com.katbrew.entities.jooq.db.tables.Announcements;
import com.katbrew.entities.jooq.db.tables.Balance;
import com.katbrew.entities.jooq.db.tables.FetchData;
import com.katbrew.entities.jooq.db.tables.Holder;
import com.katbrew.entities.jooq.db.tables.LastUpdate;
import com.katbrew.entities.jooq.db.tables.NftBalance;
import com.katbrew.entities.jooq.db.tables.NftCollection;
import com.katbrew.entities.jooq.db.tables.NftCollectionEntry;
import com.katbrew.entities.jooq.db.tables.NftCollectionInfo;
import com.katbrew.entities.jooq.db.tables.NftTransaction;
import com.katbrew.entities.jooq.db.tables.PriceData;
import com.katbrew.entities.jooq.db.tables.Token;
import com.katbrew.entities.jooq.db.tables.TopHolder;
import com.katbrew.entities.jooq.db.tables.Transaction;
import com.katbrew.entities.jooq.db.tables.Users;
import com.katbrew.entities.jooq.db.tables.Whitelist;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Advertisements</code>.
     */
    public static final Advertisements ADVERTISEMENTS = Advertisements.ADVERTISEMENTS;

    /**
     * The table <code>public.Announcements</code>.
     */
    public static final Announcements ANNOUNCEMENTS = Announcements.ANNOUNCEMENTS;

    /**
     * The table <code>public.Balance</code>.
     */
    public static final Balance BALANCE = Balance.BALANCE;

    /**
     * The table <code>public.fetch_data</code>.
     */
    public static final FetchData FETCH_DATA = FetchData.FETCH_DATA;

    /**
     * The table <code>public.Holder</code>.
     */
    public static final Holder HOLDER = Holder.HOLDER;

    /**
     * The table <code>public.Last_Update</code>.
     */
    public static final LastUpdate LAST_UPDATE = LastUpdate.LAST_UPDATE;

    /**
     * The table <code>public.nft_balance</code>.
     */
    public static final NftBalance NFT_BALANCE = NftBalance.NFT_BALANCE;

    /**
     * The table <code>public.nft_collection</code>.
     */
    public static final NftCollection NFT_COLLECTION = NftCollection.NFT_COLLECTION;

    /**
     * The table <code>public.nft_collection_entry</code>.
     */
    public static final NftCollectionEntry NFT_COLLECTION_ENTRY = NftCollectionEntry.NFT_COLLECTION_ENTRY;

    /**
     * The table <code>public.nft_collection_info</code>.
     */
    public static final NftCollectionInfo NFT_COLLECTION_INFO = NftCollectionInfo.NFT_COLLECTION_INFO;

    /**
     * The table <code>public.nft_transaction</code>.
     */
    public static final NftTransaction NFT_TRANSACTION = NftTransaction.NFT_TRANSACTION;

    /**
     * The table <code>public.Price_Data</code>.
     */
    public static final PriceData PRICE_DATA = PriceData.PRICE_DATA;

    /**
     * The table <code>public.Token</code>.
     */
    public static final Token TOKEN = Token.TOKEN;

    /**
     * The table <code>public.Top_Holder</code>.
     */
    public static final TopHolder TOP_HOLDER = TopHolder.TOP_HOLDER;

    /**
     * The table <code>public.Transaction</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>public.Users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.Whitelist</code>.
     */
    public static final Whitelist WHITELIST = Whitelist.WHITELIST;
}
