/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db;


import com.katbrew.entities.jooq.db.tables.Announcements;
import com.katbrew.entities.jooq.db.tables.Balance;
import com.katbrew.entities.jooq.db.tables.Holder;
import com.katbrew.entities.jooq.db.tables.LastUpdate;
import com.katbrew.entities.jooq.db.tables.PriceData;
import com.katbrew.entities.jooq.db.tables.Token;
import com.katbrew.entities.jooq.db.tables.Transaction;
import com.katbrew.entities.jooq.db.tables.Users;
import com.katbrew.entities.jooq.db.tables.Whitelist;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Announcements</code>.
     */
    public static final Announcements ANNOUNCEMENTS = Announcements.ANNOUNCEMENTS;

    /**
     * The table <code>public.Balance</code>.
     */
    public static final Balance BALANCE = Balance.BALANCE;

    /**
     * The table <code>public.Holder</code>.
     */
    public static final Holder HOLDER = Holder.HOLDER;

    /**
     * The table <code>public.Last_Update</code>.
     */
    public static final LastUpdate LAST_UPDATE = LastUpdate.LAST_UPDATE;

    /**
     * The table <code>public.Price_Data</code>.
     */
    public static final PriceData PRICE_DATA = PriceData.PRICE_DATA;

    /**
     * The table <code>public.Token</code>.
     */
    public static final Token TOKEN = Token.TOKEN;

    /**
     * The table <code>public.Transaction</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>public.Users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.Whitelist</code>.
     */
    public static final Whitelist WHITELIST = Whitelist.WHITELIST;
}
