/*
 * This file is generated by jOOQ.
 */
package com.nacho.entities.jooq.db.tables;


import com.nacho.entities.jooq.db.Keys;
import com.nacho.entities.jooq.db.Public;
import com.nacho.entities.jooq.db.tables.Token.TokenPath;
import com.nacho.entities.jooq.db.tables.records.PriceDataRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PriceData extends TableImpl<PriceDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.Price_Data</code>
     */
    public static final PriceData PRICE_DATA = new PriceData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PriceDataRecord> getRecordType() {
        return PriceDataRecord.class;
    }

    /**
     * The column <code>public.Price_Data.id</code>.
     */
    public final TableField<PriceDataRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.Price_Data.fk_token</code>.
     */
    public final TableField<PriceDataRecord, Integer> FK_TOKEN = createField(DSL.name("fk_token"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.Price_Data.value_kas</code>.
     */
    public final TableField<PriceDataRecord, Double> VALUE_KAS = createField(DSL.name("value_kas"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.Price_Data.value_usd</code>.
     */
    public final TableField<PriceDataRecord, Double> VALUE_USD = createField(DSL.name("value_usd"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.Price_Data.change_24h</code>.
     */
    public final TableField<PriceDataRecord, Double> CHANGE_24H = createField(DSL.name("change_24h"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.Price_Data.timestamp</code>.
     */
    public final TableField<PriceDataRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private PriceData(Name alias, Table<PriceDataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PriceData(Name alias, Table<PriceDataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.Price_Data</code> table reference
     */
    public PriceData(String alias) {
        this(DSL.name(alias), PRICE_DATA);
    }

    /**
     * Create an aliased <code>public.Price_Data</code> table reference
     */
    public PriceData(Name alias) {
        this(alias, PRICE_DATA);
    }

    /**
     * Create a <code>public.Price_Data</code> table reference
     */
    public PriceData() {
        this(DSL.name("Price_Data"), null);
    }

    public <O extends Record> PriceData(Table<O> path, ForeignKey<O, PriceDataRecord> childPath, InverseForeignKey<O, PriceDataRecord> parentPath) {
        super(path, childPath, parentPath, PRICE_DATA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PriceDataPath extends PriceData implements Path<PriceDataRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PriceDataPath(Table<O> path, ForeignKey<O, PriceDataRecord> childPath, InverseForeignKey<O, PriceDataRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PriceDataPath(Name alias, Table<PriceDataRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PriceDataPath as(String alias) {
            return new PriceDataPath(DSL.name(alias), this);
        }

        @Override
        public PriceDataPath as(Name alias) {
            return new PriceDataPath(alias, this);
        }

        @Override
        public PriceDataPath as(Table<?> alias) {
            return new PriceDataPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PriceDataRecord, Long> getIdentity() {
        return (Identity<PriceDataRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PriceDataRecord> getPrimaryKey() {
        return Keys.PK_PRICE_DATA;
    }

    @Override
    public List<ForeignKey<PriceDataRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRICE_DATA__FK_PRICE_DATA_TOKEN);
    }

    private transient TokenPath _token;

    /**
     * Get the implicit join path to the <code>public.Token</code> table.
     */
    public TokenPath token() {
        if (_token == null)
            _token = new TokenPath(this, Keys.PRICE_DATA__FK_PRICE_DATA_TOKEN, null);

        return _token;
    }

    @Override
    public PriceData as(String alias) {
        return new PriceData(DSL.name(alias), this);
    }

    @Override
    public PriceData as(Name alias) {
        return new PriceData(alias, this);
    }

    @Override
    public PriceData as(Table<?> alias) {
        return new PriceData(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PriceData rename(String name) {
        return new PriceData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PriceData rename(Name name) {
        return new PriceData(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PriceData rename(Table<?> name) {
        return new PriceData(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriceData where(Condition condition) {
        return new PriceData(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriceData where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriceData where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriceData where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriceData where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriceData where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriceData where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriceData where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriceData whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriceData whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
