/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.pojos;


import com.katbrew.entities.jooq.db.tables.interfaces.IAnnouncements;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Announcements implements IAnnouncements {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String title;
    private String text;
    private String imageUrl;
    private LocalDateTime timestamp;

    public Announcements() {}

    public Announcements(IAnnouncements value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.text = value.getText();
        this.imageUrl = value.getImageUrl();
        this.timestamp = value.getTimestamp();
    }

    public Announcements(
        Integer id,
        String title,
        String text,
        String imageUrl,
        LocalDateTime timestamp
    ) {
        this.id = id;
        this.title = title;
        this.text = text;
        this.imageUrl = imageUrl;
        this.timestamp = timestamp;
    }

    /**
     * Getter for <code>public.Announcements.id</code>.
     */
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.Announcements.id</code>.
     */
    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.Announcements.title</code>.
     */
    @Override
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.Announcements.title</code>.
     */
    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.Announcements.text</code>.
     */
    @Override
    public String getText() {
        return this.text;
    }

    /**
     * Setter for <code>public.Announcements.text</code>.
     */
    @Override
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for <code>public.Announcements.image_url</code>.
     */
    @Override
    public String getImageUrl() {
        return this.imageUrl;
    }

    /**
     * Setter for <code>public.Announcements.image_url</code>.
     */
    @Override
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Getter for <code>public.Announcements.timestamp</code>.
     */
    @Override
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Setter for <code>public.Announcements.timestamp</code>.
     */
    @Override
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Announcements other = (Announcements) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.text == null) {
            if (other.text != null)
                return false;
        }
        else if (!this.text.equals(other.text))
            return false;
        if (this.imageUrl == null) {
            if (other.imageUrl != null)
                return false;
        }
        else if (!this.imageUrl.equals(other.imageUrl))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.text == null) ? 0 : this.text.hashCode());
        result = prime * result + ((this.imageUrl == null) ? 0 : this.imageUrl.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Announcements (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(text);
        sb.append(", ").append(imageUrl);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAnnouncements from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setText(from.getText());
        setImageUrl(from.getImageUrl());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IAnnouncements> E into(E into) {
        into.from(this);
        return into;
    }
}
