/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.pojos;


import com.katbrew.entities.jooq.db.tables.interfaces.ILastUpdate;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LastUpdate implements ILastUpdate {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private LocalDateTime timestamp;

    public LastUpdate() {}

    public LastUpdate(ILastUpdate value) {
        this.id = value.getId();
        this.timestamp = value.getTimestamp();
    }

    public LastUpdate(
        Integer id,
        LocalDateTime timestamp
    ) {
        this.id = id;
        this.timestamp = timestamp;
    }

    /**
     * Getter for <code>public.Last_Update.id</code>.
     */
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.Last_Update.id</code>.
     */
    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.Last_Update.timestamp</code>.
     */
    @Override
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Setter for <code>public.Last_Update.timestamp</code>.
     */
    @Override
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LastUpdate other = (LastUpdate) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LastUpdate (");

        sb.append(id);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILastUpdate from) {
        setId(from.getId());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends ILastUpdate> E into(E into) {
        into.from(this);
        return into;
    }
}
