/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.pojos;


import com.katbrew.entities.jooq.db.tables.interfaces.ITransaction;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction implements ITransaction {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer fkToken;
    private String hashrev;
    private String p;
    private String op;
    private String amt;
    private String from;
    private String to;
    private String opScore;
    private String feeRev;
    private String txAccept;
    private String opAccept;
    private String opError;
    private String checkpoint;
    private Long max;
    private Long lim;
    private Long pre;
    private Long mtsAdd;
    private Long mtsMod;
    private Integer dec;
    private LocalDateTime timestamp;

    public Transaction() {}

    public Transaction(ITransaction value) {
        this.id = value.getId();
        this.fkToken = value.getFkToken();
        this.hashrev = value.getHashrev();
        this.p = value.getP();
        this.op = value.getOp();
        this.amt = value.getAmt();
        this.from = value.getFrom();
        this.to = value.getTo();
        this.opScore = value.getOpScore();
        this.feeRev = value.getFeeRev();
        this.txAccept = value.getTxAccept();
        this.opAccept = value.getOpAccept();
        this.opError = value.getOpError();
        this.checkpoint = value.getCheckpoint();
        this.max = value.getMax();
        this.lim = value.getLim();
        this.pre = value.getPre();
        this.mtsAdd = value.getMtsAdd();
        this.mtsMod = value.getMtsMod();
        this.dec = value.getDec();
        this.timestamp = value.getTimestamp();
    }

    public Transaction(
        Long id,
        Integer fkToken,
        String hashrev,
        String p,
        String op,
        String amt,
        String from,
        String to,
        String opScore,
        String feeRev,
        String txAccept,
        String opAccept,
        String opError,
        String checkpoint,
        Long max,
        Long lim,
        Long pre,
        Long mtsAdd,
        Long mtsMod,
        Integer dec,
        LocalDateTime timestamp
    ) {
        this.id = id;
        this.fkToken = fkToken;
        this.hashrev = hashrev;
        this.p = p;
        this.op = op;
        this.amt = amt;
        this.from = from;
        this.to = to;
        this.opScore = opScore;
        this.feeRev = feeRev;
        this.txAccept = txAccept;
        this.opAccept = opAccept;
        this.opError = opError;
        this.checkpoint = checkpoint;
        this.max = max;
        this.lim = lim;
        this.pre = pre;
        this.mtsAdd = mtsAdd;
        this.mtsMod = mtsMod;
        this.dec = dec;
        this.timestamp = timestamp;
    }

    /**
     * Getter for <code>public.Transaction.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.Transaction.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.Transaction.fk_token</code>.
     */
    @Override
    public Integer getFkToken() {
        return this.fkToken;
    }

    /**
     * Setter for <code>public.Transaction.fk_token</code>.
     */
    @Override
    public void setFkToken(Integer fkToken) {
        this.fkToken = fkToken;
    }

    /**
     * Getter for <code>public.Transaction.hashrev</code>.
     */
    @Override
    public String getHashrev() {
        return this.hashrev;
    }

    /**
     * Setter for <code>public.Transaction.hashrev</code>.
     */
    @Override
    public void setHashrev(String hashrev) {
        this.hashrev = hashrev;
    }

    /**
     * Getter for <code>public.Transaction.p</code>.
     */
    @Override
    public String getP() {
        return this.p;
    }

    /**
     * Setter for <code>public.Transaction.p</code>.
     */
    @Override
    public void setP(String p) {
        this.p = p;
    }

    /**
     * Getter for <code>public.Transaction.op</code>.
     */
    @Override
    public String getOp() {
        return this.op;
    }

    /**
     * Setter for <code>public.Transaction.op</code>.
     */
    @Override
    public void setOp(String op) {
        this.op = op;
    }

    /**
     * Getter for <code>public.Transaction.amt</code>.
     */
    @Override
    public String getAmt() {
        return this.amt;
    }

    /**
     * Setter for <code>public.Transaction.amt</code>.
     */
    @Override
    public void setAmt(String amt) {
        this.amt = amt;
    }

    /**
     * Getter for <code>public.Transaction.from</code>.
     */
    @Override
    public String getFrom() {
        return this.from;
    }

    /**
     * Setter for <code>public.Transaction.from</code>.
     */
    @Override
    public void setFrom(String from) {
        this.from = from;
    }

    /**
     * Getter for <code>public.Transaction.to</code>.
     */
    @Override
    public String getTo() {
        return this.to;
    }

    /**
     * Setter for <code>public.Transaction.to</code>.
     */
    @Override
    public void setTo(String to) {
        this.to = to;
    }

    /**
     * Getter for <code>public.Transaction.op_score</code>.
     */
    @Override
    public String getOpScore() {
        return this.opScore;
    }

    /**
     * Setter for <code>public.Transaction.op_score</code>.
     */
    @Override
    public void setOpScore(String opScore) {
        this.opScore = opScore;
    }

    /**
     * Getter for <code>public.Transaction.fee_rev</code>.
     */
    @Override
    public String getFeeRev() {
        return this.feeRev;
    }

    /**
     * Setter for <code>public.Transaction.fee_rev</code>.
     */
    @Override
    public void setFeeRev(String feeRev) {
        this.feeRev = feeRev;
    }

    /**
     * Getter for <code>public.Transaction.tx_accept</code>.
     */
    @Override
    public String getTxAccept() {
        return this.txAccept;
    }

    /**
     * Setter for <code>public.Transaction.tx_accept</code>.
     */
    @Override
    public void setTxAccept(String txAccept) {
        this.txAccept = txAccept;
    }

    /**
     * Getter for <code>public.Transaction.op_accept</code>.
     */
    @Override
    public String getOpAccept() {
        return this.opAccept;
    }

    /**
     * Setter for <code>public.Transaction.op_accept</code>.
     */
    @Override
    public void setOpAccept(String opAccept) {
        this.opAccept = opAccept;
    }

    /**
     * Getter for <code>public.Transaction.op_error</code>.
     */
    @Override
    public String getOpError() {
        return this.opError;
    }

    /**
     * Setter for <code>public.Transaction.op_error</code>.
     */
    @Override
    public void setOpError(String opError) {
        this.opError = opError;
    }

    /**
     * Getter for <code>public.Transaction.checkpoint</code>.
     */
    @Override
    public String getCheckpoint() {
        return this.checkpoint;
    }

    /**
     * Setter for <code>public.Transaction.checkpoint</code>.
     */
    @Override
    public void setCheckpoint(String checkpoint) {
        this.checkpoint = checkpoint;
    }

    /**
     * Getter for <code>public.Transaction.max</code>.
     */
    @Override
    public Long getMax() {
        return this.max;
    }

    /**
     * Setter for <code>public.Transaction.max</code>.
     */
    @Override
    public void setMax(Long max) {
        this.max = max;
    }

    /**
     * Getter for <code>public.Transaction.lim</code>.
     */
    @Override
    public Long getLim() {
        return this.lim;
    }

    /**
     * Setter for <code>public.Transaction.lim</code>.
     */
    @Override
    public void setLim(Long lim) {
        this.lim = lim;
    }

    /**
     * Getter for <code>public.Transaction.pre</code>.
     */
    @Override
    public Long getPre() {
        return this.pre;
    }

    /**
     * Setter for <code>public.Transaction.pre</code>.
     */
    @Override
    public void setPre(Long pre) {
        this.pre = pre;
    }

    /**
     * Getter for <code>public.Transaction.mts_add</code>.
     */
    @Override
    public Long getMtsAdd() {
        return this.mtsAdd;
    }

    /**
     * Setter for <code>public.Transaction.mts_add</code>.
     */
    @Override
    public void setMtsAdd(Long mtsAdd) {
        this.mtsAdd = mtsAdd;
    }

    /**
     * Getter for <code>public.Transaction.mts_mod</code>.
     */
    @Override
    public Long getMtsMod() {
        return this.mtsMod;
    }

    /**
     * Setter for <code>public.Transaction.mts_mod</code>.
     */
    @Override
    public void setMtsMod(Long mtsMod) {
        this.mtsMod = mtsMod;
    }

    /**
     * Getter for <code>public.Transaction.dec</code>.
     */
    @Override
    public Integer getDec() {
        return this.dec;
    }

    /**
     * Setter for <code>public.Transaction.dec</code>.
     */
    @Override
    public void setDec(Integer dec) {
        this.dec = dec;
    }

    /**
     * Getter for <code>public.Transaction.timestamp</code>.
     */
    @Override
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Setter for <code>public.Transaction.timestamp</code>.
     */
    @Override
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Transaction other = (Transaction) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fkToken == null) {
            if (other.fkToken != null)
                return false;
        }
        else if (!this.fkToken.equals(other.fkToken))
            return false;
        if (this.hashrev == null) {
            if (other.hashrev != null)
                return false;
        }
        else if (!this.hashrev.equals(other.hashrev))
            return false;
        if (this.p == null) {
            if (other.p != null)
                return false;
        }
        else if (!this.p.equals(other.p))
            return false;
        if (this.op == null) {
            if (other.op != null)
                return false;
        }
        else if (!this.op.equals(other.op))
            return false;
        if (this.amt == null) {
            if (other.amt != null)
                return false;
        }
        else if (!this.amt.equals(other.amt))
            return false;
        if (this.from == null) {
            if (other.from != null)
                return false;
        }
        else if (!this.from.equals(other.from))
            return false;
        if (this.to == null) {
            if (other.to != null)
                return false;
        }
        else if (!this.to.equals(other.to))
            return false;
        if (this.opScore == null) {
            if (other.opScore != null)
                return false;
        }
        else if (!this.opScore.equals(other.opScore))
            return false;
        if (this.feeRev == null) {
            if (other.feeRev != null)
                return false;
        }
        else if (!this.feeRev.equals(other.feeRev))
            return false;
        if (this.txAccept == null) {
            if (other.txAccept != null)
                return false;
        }
        else if (!this.txAccept.equals(other.txAccept))
            return false;
        if (this.opAccept == null) {
            if (other.opAccept != null)
                return false;
        }
        else if (!this.opAccept.equals(other.opAccept))
            return false;
        if (this.opError == null) {
            if (other.opError != null)
                return false;
        }
        else if (!this.opError.equals(other.opError))
            return false;
        if (this.checkpoint == null) {
            if (other.checkpoint != null)
                return false;
        }
        else if (!this.checkpoint.equals(other.checkpoint))
            return false;
        if (this.max == null) {
            if (other.max != null)
                return false;
        }
        else if (!this.max.equals(other.max))
            return false;
        if (this.lim == null) {
            if (other.lim != null)
                return false;
        }
        else if (!this.lim.equals(other.lim))
            return false;
        if (this.pre == null) {
            if (other.pre != null)
                return false;
        }
        else if (!this.pre.equals(other.pre))
            return false;
        if (this.mtsAdd == null) {
            if (other.mtsAdd != null)
                return false;
        }
        else if (!this.mtsAdd.equals(other.mtsAdd))
            return false;
        if (this.mtsMod == null) {
            if (other.mtsMod != null)
                return false;
        }
        else if (!this.mtsMod.equals(other.mtsMod))
            return false;
        if (this.dec == null) {
            if (other.dec != null)
                return false;
        }
        else if (!this.dec.equals(other.dec))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fkToken == null) ? 0 : this.fkToken.hashCode());
        result = prime * result + ((this.hashrev == null) ? 0 : this.hashrev.hashCode());
        result = prime * result + ((this.p == null) ? 0 : this.p.hashCode());
        result = prime * result + ((this.op == null) ? 0 : this.op.hashCode());
        result = prime * result + ((this.amt == null) ? 0 : this.amt.hashCode());
        result = prime * result + ((this.from == null) ? 0 : this.from.hashCode());
        result = prime * result + ((this.to == null) ? 0 : this.to.hashCode());
        result = prime * result + ((this.opScore == null) ? 0 : this.opScore.hashCode());
        result = prime * result + ((this.feeRev == null) ? 0 : this.feeRev.hashCode());
        result = prime * result + ((this.txAccept == null) ? 0 : this.txAccept.hashCode());
        result = prime * result + ((this.opAccept == null) ? 0 : this.opAccept.hashCode());
        result = prime * result + ((this.opError == null) ? 0 : this.opError.hashCode());
        result = prime * result + ((this.checkpoint == null) ? 0 : this.checkpoint.hashCode());
        result = prime * result + ((this.max == null) ? 0 : this.max.hashCode());
        result = prime * result + ((this.lim == null) ? 0 : this.lim.hashCode());
        result = prime * result + ((this.pre == null) ? 0 : this.pre.hashCode());
        result = prime * result + ((this.mtsAdd == null) ? 0 : this.mtsAdd.hashCode());
        result = prime * result + ((this.mtsMod == null) ? 0 : this.mtsMod.hashCode());
        result = prime * result + ((this.dec == null) ? 0 : this.dec.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transaction (");

        sb.append(id);
        sb.append(", ").append(fkToken);
        sb.append(", ").append(hashrev);
        sb.append(", ").append(p);
        sb.append(", ").append(op);
        sb.append(", ").append(amt);
        sb.append(", ").append(from);
        sb.append(", ").append(to);
        sb.append(", ").append(opScore);
        sb.append(", ").append(feeRev);
        sb.append(", ").append(txAccept);
        sb.append(", ").append(opAccept);
        sb.append(", ").append(opError);
        sb.append(", ").append(checkpoint);
        sb.append(", ").append(max);
        sb.append(", ").append(lim);
        sb.append(", ").append(pre);
        sb.append(", ").append(mtsAdd);
        sb.append(", ").append(mtsMod);
        sb.append(", ").append(dec);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITransaction from) {
        setId(from.getId());
        setFkToken(from.getFkToken());
        setHashrev(from.getHashrev());
        setP(from.getP());
        setOp(from.getOp());
        setAmt(from.getAmt());
        setFrom(from.getFrom());
        setTo(from.getTo());
        setOpScore(from.getOpScore());
        setFeeRev(from.getFeeRev());
        setTxAccept(from.getTxAccept());
        setOpAccept(from.getOpAccept());
        setOpError(from.getOpError());
        setCheckpoint(from.getCheckpoint());
        setMax(from.getMax());
        setLim(from.getLim());
        setPre(from.getPre());
        setMtsAdd(from.getMtsAdd());
        setMtsMod(from.getMtsMod());
        setDec(from.getDec());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends ITransaction> E into(E into) {
        into.from(this);
        return into;
    }
}
