/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.records;


import com.katbrew.entities.jooq.db.tables.Balance;
import com.katbrew.entities.jooq.db.tables.interfaces.IBalance;

import java.math.BigInteger;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BalanceRecord extends UpdatableRecordImpl<BalanceRecord> implements IBalance {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Balance.id</code>.
     */
    @Override
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Balance.id</code>.
     */
    @Override
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>public.Balance.holder_id</code>.
     */
    @Override
    public void setHolderId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Balance.holder_id</code>.
     */
    @Override
    public BigInteger getHolderId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>public.Balance.balance</code>.
     */
    @Override
    public void setBalance(BigInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Balance.balance</code>.
     */
    @Override
    public BigInteger getBalance() {
        return (BigInteger) get(2);
    }

    /**
     * Setter for <code>public.Balance.fk_token</code>.
     */
    @Override
    public void setFkToken(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.Balance.fk_token</code>.
     */
    @Override
    public Integer getFkToken() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBalance from) {
        setId(from.getId());
        setHolderId(from.getHolderId());
        setBalance(from.getBalance());
        setFkToken(from.getFkToken());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IBalance> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BalanceRecord
     */
    public BalanceRecord() {
        super(Balance.BALANCE);
    }

    /**
     * Create a detached, initialised BalanceRecord
     */
    public BalanceRecord(BigInteger id, BigInteger holderId, BigInteger balance, Integer fkToken) {
        super(Balance.BALANCE);

        setId(id);
        setHolderId(holderId);
        setBalance(balance);
        setFkToken(fkToken);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BalanceRecord
     */
    public BalanceRecord(com.katbrew.entities.jooq.db.tables.pojos.Balance value) {
        super(Balance.BALANCE);

        if (value != null) {
            setId(value.getId());
            setHolderId(value.getHolderId());
            setBalance(value.getBalance());
            setFkToken(value.getFkToken());
            resetChangedOnNotNull();
        }
    }
}
