/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.records;


import com.katbrew.entities.jooq.db.tables.CodeWordings;
import com.katbrew.entities.jooq.db.tables.interfaces.ICodeWordings;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeWordingsRecord extends UpdatableRecordImpl<CodeWordingsRecord> implements ICodeWordings {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_wordings.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_wordings.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.code_wordings.identifier</code>.
     */
    @Override
    public void setIdentifier(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_wordings.identifier</code>.
     */
    @Override
    public String getIdentifier() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ICodeWordings from) {
        setId(from.getId());
        setIdentifier(from.getIdentifier());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends ICodeWordings> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeWordingsRecord
     */
    public CodeWordingsRecord() {
        super(CodeWordings.CODE_WORDINGS);
    }

    /**
     * Create a detached, initialised CodeWordingsRecord
     */
    public CodeWordingsRecord(Integer id, String identifier) {
        super(CodeWordings.CODE_WORDINGS);

        setId(id);
        setIdentifier(identifier);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CodeWordingsRecord
     */
    public CodeWordingsRecord(com.katbrew.entities.jooq.db.tables.pojos.CodeWordings value) {
        super(CodeWordings.CODE_WORDINGS);

        if (value != null) {
            setId(value.getId());
            setIdentifier(value.getIdentifier());
            resetChangedOnNotNull();
        }
    }
}
