/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.records;


import com.katbrew.entities.jooq.db.tables.FetchData;
import com.katbrew.entities.jooq.db.tables.interfaces.IFetchData;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FetchDataRecord extends UpdatableRecordImpl<FetchDataRecord> implements IFetchData {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fetch_data.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fetch_data.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.fetch_data.identifier</code>.
     */
    @Override
    public void setIdentifier(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fetch_data.identifier</code>.
     */
    @Override
    public String getIdentifier() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.fetch_data.data</code>.
     */
    @Override
    public void setData(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fetch_data.data</code>.
     */
    @Override
    public String getData() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IFetchData from) {
        setId(from.getId());
        setIdentifier(from.getIdentifier());
        setData(from.getData());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IFetchData> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FetchDataRecord
     */
    public FetchDataRecord() {
        super(FetchData.FETCH_DATA);
    }

    /**
     * Create a detached, initialised FetchDataRecord
     */
    public FetchDataRecord(Integer id, String identifier, String data) {
        super(FetchData.FETCH_DATA);

        setId(id);
        setIdentifier(identifier);
        setData(data);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FetchDataRecord
     */
    public FetchDataRecord(com.katbrew.entities.jooq.db.tables.pojos.FetchData value) {
        super(FetchData.FETCH_DATA);

        if (value != null) {
            setId(value.getId());
            setIdentifier(value.getIdentifier());
            setData(value.getData());
            resetChangedOnNotNull();
        }
    }
}
