/*
 * This file is generated by jOOQ.
 */
package com.katbrew.entities.jooq.db.tables.records;


import com.katbrew.entities.jooq.db.tables.LastUpdate;
import com.katbrew.entities.jooq.db.tables.interfaces.ILastUpdate;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LastUpdateRecord extends UpdatableRecordImpl<LastUpdateRecord> implements ILastUpdate {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Last_Update.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Last_Update.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Last_Update.timestamp</code>.
     */
    @Override
    public void setTimestamp(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Last_Update.timestamp</code>.
     */
    @Override
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILastUpdate from) {
        setId(from.getId());
        setTimestamp(from.getTimestamp());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends ILastUpdate> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LastUpdateRecord
     */
    public LastUpdateRecord() {
        super(LastUpdate.LAST_UPDATE);
    }

    /**
     * Create a detached, initialised LastUpdateRecord
     */
    public LastUpdateRecord(Integer id, LocalDateTime timestamp) {
        super(LastUpdate.LAST_UPDATE);

        setId(id);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LastUpdateRecord
     */
    public LastUpdateRecord(com.katbrew.entities.jooq.db.tables.pojos.LastUpdate value) {
        super(LastUpdate.LAST_UPDATE);

        if (value != null) {
            setId(value.getId());
            setTimestamp(value.getTimestamp());
            resetChangedOnNotNull();
        }
    }
}
