/*
 * This file is generated by jOOQ.
 */
package com.nacho.entities.jooq.db.tables.daos;


import com.nacho.entities.jooq.db.tables.Lastupdate;
import com.nacho.entities.jooq.db.tables.records.LastupdateRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LastupdateDao extends DAOImpl<LastupdateRecord, com.nacho.entities.jooq.db.tables.pojos.Lastupdate, Integer> {

    /**
     * Create a new LastupdateDao without any configuration
     */
    public LastupdateDao() {
        super(Lastupdate.LASTUPDATE, com.nacho.entities.jooq.db.tables.pojos.Lastupdate.class);
    }

    /**
     * Create a new LastupdateDao with an attached configuration
     */
    public LastupdateDao(Configuration configuration) {
        super(Lastupdate.LASTUPDATE, com.nacho.entities.jooq.db.tables.pojos.Lastupdate.class, configuration);
    }

    @Override
    public Integer getId(com.nacho.entities.jooq.db.tables.pojos.Lastupdate object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.nacho.entities.jooq.db.tables.pojos.Lastupdate> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Lastupdate.LASTUPDATE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nacho.entities.jooq.db.tables.pojos.Lastupdate> fetchById(Integer... values) {
        return fetch(Lastupdate.LASTUPDATE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nacho.entities.jooq.db.tables.pojos.Lastupdate fetchOneById(Integer value) {
        return fetchOne(Lastupdate.LASTUPDATE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.nacho.entities.jooq.db.tables.pojos.Lastupdate> fetchOptionalById(Integer value) {
        return fetchOptional(Lastupdate.LASTUPDATE.ID, value);
    }

    /**
     * Fetch records that have <code>timestamp BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.nacho.entities.jooq.db.tables.pojos.Lastupdate> fetchRangeOfTimestamp(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Lastupdate.LASTUPDATE.TIMESTAMP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<com.nacho.entities.jooq.db.tables.pojos.Lastupdate> fetchByTimestamp(LocalDateTime... values) {
        return fetch(Lastupdate.LASTUPDATE.TIMESTAMP, values);
    }
}
